# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: drone_control.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'drone_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x64rone_control.proto\x12\x0c\x64ronecontrol\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x0cStartLinkReq\x12\x0c\n\x04port\x18\x01 \x01(\t\x12\x11\n\tbaud_rate\x18\x02 \x01(\x05\"1\n\rStartLinkResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\"\n\x0eSetChannelsReq\x12\x10\n\x08\x63hannels\x18\x01 \x03(\x05\"S\n\nStatusResp\x12\r\n\x05\x61rmed\x18\x01 \x01(\x08\x12\x11\n\tconnected\x18\x02 \x01(\x08\x12\x10\n\x08\x63hannels\x18\x03 \x03(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x32\xd0\x03\n\x0c\x44roneControl\x12\x44\n\tstartLink\x12\x1a.dronecontrol.StartLinkReq\x1a\x1b.dronecontrol.StartLinkResp\x12:\n\x08stopLink\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x43\n\x0bsetChannels\x12\x1c.dronecontrol.SetChannelsReq\x1a\x16.google.protobuf.Empty\x12:\n\x08\x61rmDrone\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12=\n\x0b\x64isarmDrone\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12?\n\rresetControls\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12=\n\tgetStatus\x12\x16.google.protobuf.Empty\x1a\x18.dronecontrol.StatusRespb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'drone_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTLINKREQ']._serialized_start=66
  _globals['_STARTLINKREQ']._serialized_end=113
  _globals['_STARTLINKRESP']._serialized_start=115
  _globals['_STARTLINKRESP']._serialized_end=164
  _globals['_SETCHANNELSREQ']._serialized_start=166
  _globals['_SETCHANNELSREQ']._serialized_end=200
  _globals['_STATUSRESP']._serialized_start=202
  _globals['_STATUSRESP']._serialized_end=285
  _globals['_DRONECONTROL']._serialized_start=288
  _globals['_DRONECONTROL']._serialized_end=752
# @@protoc_insertion_point(module_scope)
